import { Geist, Geist_Mono,Open_Sans} from "next/font/google";
import "./globals.css";
import Header from "../header/page";

const opensans = Open_Sans({
  subsets: ['latin'],
  weight: ["700"],
  fallback: ['sans-serif'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Infomin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
